### Variables
@baseUrl = http://localhost:8080/api/v1
# Ganti token ini dengan token yang didapatkan dari response Login
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

### 1. Register User 1 (Kevin)
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "kevin@example.com",
  "password": "password123",
  "full_name": "Kevin Pratama"
}

### 2. Register User 2 (Budi)
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "budi@example.com",
  "password": "password123",
  "full_name": "Budi Santoso"
}

### 3. Login User 1 (Kevin) - Dapatkan Token
# @name loginKevin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "kevin@example.com",
  "password": "password123"
}

### 4. Cek Saldo Dompet Kevin (Protected)
GET {{baseUrl}}/wallets/me
Content-Type: application/json
Authorization: Bearer {{loginKevin.response.body.data.token}}

### 5. Top Up Saldo Kevin Rp500.000 (Protected)
POST {{baseUrl}}/wallets/topup
Content-Type: application/json
Authorization: Bearer {{loginKevin.response.body.data.token}}

{
  "amount": 500000
}

### 6. Transfer Saldo Atomik dari Kevin ke Budi (UserID: 2) Rp150.000 (Protected)
POST {{baseUrl}}/wallets/transfer
Content-Type: application/json
Authorization: Bearer {{loginKevin.response.body.data.token}}

{
  "to_user_id": 2,
  "amount": 150000
}

### 7. Uji Gagal Transfer (Saldo Kurang)
POST {{baseUrl}}/wallets/transfer
Content-Type: application/json
Authorization: Bearer {{loginKevin.response.body.data.token}}

{
  "to_user_id": 2,
  "amount": 10000000
}

### 8. Ambil Semua Produk (Public)
GET {{baseUrl}}/products
Content-Type: application/json
